import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Post from "../components/Post";
import Bio from "../components/Bio";
import PostForm from "../components/PostForm";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot="https://media-exp1.licdn.com/dms/image/C4E03AQF0iEGLK8lANQ/profile-displayphoto-shrink_800_800/0/1554837206100?e=1649289600&v=beta&t=SPj4WQPyeC9HSt09nFydzfNZ5D-qAh93z10TJkS2GEE"
          layout="fill"
          name="Ivan Romero"
          tagline="I am learning!"
          role="Sofware Engineer"
        />
        <ul className={styles.posts}>
          <li>
            <Post
              content="hey i am new post"
              date={new Date().toLocaleDateString()}
              likes={10}
            />
          </li>
          <li>
            <Post
              content="Hey This is another post lolol"
              date={new Date().toLocaleDateString()}
              likes={12}
            />
          </li>
          <li>
            <Post
              content="Yeeters"
              date={new Date().toLocaleDateString()}
              likes={19}
            />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
